name: Build and Push Docker Image

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/actions/clean-up/action.yml'
      - '.github/actions/docker-login/action.yml'
      - '.github/workflows/_docker-build.yml'
      - '.github/workflows/docker.yml'
      - 'cann/**'
      - 'python/**'
      - 'pytorch/**'
      - 'mindspore/**'
      - 'arg.json'
      - 'docker-bake.hcl'
      - '!**/*.md'
  pull_request:
    branches:
      - 'main'
    paths:
      - '.github/actions/clean-up/action.yml'
      - '.github/actions/docker-login/action.yml'
      - '.github/workflows/_docker-build.yml'
      - '.github/workflows/docker.yml'
      - 'cann/**'
      - 'python/**'
      - 'pytorch/**'
      - 'mindspore/**'
      - 'arg.json'
      - 'docker-bake.hcl'
      - '!**/*.md'
  release:
    types:
      - 'published'
  workflow_dispatch:
    inputs:
      image:
        description: 'docker image name'
        required: true
        default: 'cann'
        type: choice
        options:
          - cann
          - pytorch
          - mindspore
          - python
      args:
        description: 'build args in JSON format, such as arg.json'
        required: true
        default: '[]'
        type: string
      push:
        description: 'true to push the docker image'
        required: true
        default: false
        type: boolean

# Only cancel the previous runs when triggered by a pull request
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read
  packages: write

jobs:
  prepare:
    name: prepare
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.list-bake-files.outputs.files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List bake definition files
        id: list-bake-files
        run: |
          

  python:
    name: python
    uses: ./.github/workflows/_docker-build.yml
    with:
      target: 'python'
      push: ${{ github.event_name == 'release' || github.event.inputs.push }}
      clean-up: false
      set: |
        *.cache-from=type=gha
        *.cache-to=type=gha,mode=min
    secrets:
      DOCKERHUB_OWNER: ${{ secrets.DOCKERHUB_OWNER }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      QUAY_OWNER: ${{ secrets.QUAY_OWNER }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}

  cann:
    name: cann
    needs:
      - python
    uses: ./.github/workflows/_docker-build.yml
    with:
      target: 'cann'
      push: ${{ github.event_name == 'release' || github.event.inputs.push }}
    secrets:
      DOCKERHUB_OWNER: ${{ secrets.DOCKERHUB_OWNER }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      QUAY_OWNER: ${{ secrets.QUAY_OWNER }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}

  pytorch:
    name: pytorch
    needs:
      - cann
    uses: ./.github/workflows/_docker-build.yml
    with:
      target: 'pytorch'
      push: ${{ github.event_name == 'release' || github.event.inputs.push }}
    secrets:
      DOCKERHUB_OWNER: ${{ secrets.DOCKERHUB_OWNER }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      QUAY_OWNER: ${{ secrets.QUAY_OWNER }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}

  mindspore:
    name: mindspore
    needs:
      - cann
    uses: ./.github/workflows/_docker-build.yml
    with:
      target: 'mindspore'
      push: ${{ github.event_name == 'release' || github.event.inputs.push }}
    secrets:
      DOCKERHUB_OWNER: ${{ secrets.DOCKERHUB_OWNER }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      QUAY_OWNER: ${{ secrets.QUAY_OWNER }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
